### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'use_imvote'

### ISSUE THREAD

**Issue by koubun-ko-df** [facebookresearch/imvotenet#9]
When I ran "CUDA_VISIBLE_DEVICES=0 python train.py --use_imvotenet --log_dir log_imvotenet" and "CUDA_VISIBLE_DEVICES=0 python train.py --use_imvotenet --log_dir log_140ep --max_epoch 140 --lr_decay_steps 80,120 --lr_decay_rates 0.1,0.1", there was a TypeError. How to fix it?
![image](https://user-images.githubusercontent.com/54608650/117911022-9b850700-b30f-11eb-87eb-e093a8da9d1d.png)

**Comment by endernewton** [comment]
Looks like it is saying "use_imvote" is NOT an option

**Comment by koubun-ko-df** [comment]
> Looks like it is saying "use_imvote" is NOT an option

But in line 135 of train.py, there is "use_imvote"
![image](https://user-images.githubusercontent.com/54608650/117911593-a68c6700-b310-11eb-8231-a82a374347c5.png)

**Comment by IliasMAOUDJ** [comment]
It's `parser.add_argument('--use_imvotenet', action='store_true', help='Use ImVoteNet (instead of VoteNet) with RGB.')` so you have to use --use_imvotenet

**Comment by endernewton** [comment]
I think you want to follow the options in FLAGS, not in the function.

**Comment by FabienCode** [comment]
i have the same question, Did you solve this problem?

**Comment by DongChen06** [comment]
you should use the python files in this project . Just copy the data instead of the python files
